use chrono::{DateTime, Utc};
use serde::Serialize;

/// Pricing tier that determines the sell price for an API key.
/// `Bit` is the cheapest, `Cluster` the most expensive.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Serialize)]
pub enum Tier {
    Bit,
    Node,
    Cluster,
}

/// An upstream provider that serves model inference requests.
#[derive(Debug, Clone, Serialize)]
pub struct Provider {
    pub id: String,
    pub name: String,
    pub base_url: String,
    pub api_key: String,
    pub quantization: String,
    pub context_length: i64,
    pub max_output_length: i64,
    pub datacenter_country: String,
    pub created_at: DateTime<Utc>,
}

/// An API key stored in DynamoDB. The raw key is never stored;
/// only its SHA-256 hash (with a secret pepper) is persisted.
#[derive(Debug, Clone)]
pub struct ApiKey {
    /// UUID generated at creation time
    pub id: String,
    /// SHA-256 hash of the raw key (never expose to clients)
    pub key_hash: String,
    pub tier: Tier,
    /// Total revenue generated by this key
    pub balance_accumulated: f64,
    /// Optional spending cap; key is blocked when balance ≥ this value
    pub credit_limit: Option<f64>,
    /// When false the key is rejected as if it doesn't exist
    pub active: bool,
    pub created_at: DateTime<Utc>,
}

/// A single billing transaction recorded atomically alongside
/// idempotency, timeline, balance update, and global metrics.
#[derive(Debug, Clone, Serialize)]
pub struct Transaction {
    pub id: String,
    pub api_key_id: String,
    pub model_name: String,
    pub input_tokens: i64,
    pub output_tokens: i64,
    /// Upstream provider cost (USD)
    pub cost_basis: f64,
    /// Revenue charged to the API key (USD)
    pub revenue_generated: f64,
    pub timestamp: DateTime<Utc>,
}

/// Per-model pricing configuration (provider cost + per-tier sell prices).
/// Input and output tokens are priced separately at the provider level.
#[derive(Debug, Clone, Serialize)]
pub struct PricingConfig {
    pub model_name: String,
    pub provider_id: String,
    pub provider_cost_input_per_1m: f64,
    pub provider_cost_output_per_1m: f64,
    pub bit_price_per_1m: f64,
    pub node_price_per_1m: f64,
    pub cluster_price_per_1m: f64,
    pub min_tier: Tier,
    pub updated_at: DateTime<Utc>,
}

/// Stored idempotency lookup record (payload hash + optional cached response).
#[derive(Debug, Clone)]
pub struct IdempotencyRecord {
    pub request_hash: String,
    pub response_body: Option<String>,
}

/// Aggregated billing metrics displayed on the admin dashboard.
#[derive(Debug, Clone, Serialize)]
pub struct DashboardMetrics {
    pub total_margin: f64,
    pub total_input_tokens: i64,
    pub total_output_tokens: i64,
    pub tx_count: i64,
}

/// Cursor-based page of recent transactions (fan-out across timeline shards).
#[derive(Debug, Clone, Serialize, Default)]
pub struct RecentTransactionsPage {
    pub transactions: Vec<Transaction>,
    /// Opaque cursor for the next page
    pub next_cursor: Option<String>,
    /// Opaque cursor for the previous page (backward navigation)
    pub prev_cursor: Option<String>,
}
