#!/usr/bin/env bash
set -euo pipefail

AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID:-test}"
AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY:-test}"
AWS_REGION="${AWS_REGION:-us-east-1}"
AWS_ENDPOINT_URL_DYNAMODB="${AWS_ENDPOINT_URL_DYNAMODB:-http://127.0.0.1:8000}"
API_KEY_HASH_SECRET="${API_KEY_HASH_SECRET:-dev-secret}"
IDEMPOTENCY_TTL_SECONDS="${IDEMPOTENCY_TTL_SECONDS:-86400}"
ADMIN_BEARER_TOKEN="${ADMIN_BEARER_TOKEN:-change-me}"

export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_REGION AWS_ENDPOINT_URL_DYNAMODB
export API_KEY_HASH_SECRET IDEMPOTENCY_TTL_SECONDS ADMIN_BEARER_TOKEN

docker compose up -d dynamodb-local
./scripts/bootstrap_dynamodb_local.sh
./scripts/backfill_idempotency_ttl.sh

RUN_MODE=server \
LISTEN_ADDR="${LISTEN_ADDR:-127.0.0.1:8080}" \
NIM_BASE_URL="${NIM_BASE_URL:-https://integrate.api.nvidia.com}" \
NIM_API_KEY="${NIM_API_KEY:-replace-me}" \
PROVIDER_NAME_PREFIX="${PROVIDER_NAME_PREFIX:-TokenRouter}" \
PROVIDER_QUANTIZATION="${PROVIDER_QUANTIZATION:-fp16}" \
PROVIDER_CONTEXT_LENGTH="${PROVIDER_CONTEXT_LENGTH:-128000}" \
PROVIDER_MAX_OUTPUT_LENGTH="${PROVIDER_MAX_OUTPUT_LENGTH:-8192}" \
PROVIDER_DATACENTER_COUNTRY="${PROVIDER_DATACENTER_COUNTRY:-US}" \
MAX_INFLIGHT_REQUESTS="${MAX_INFLIGHT_REQUESTS:-200}" \
cargo run
